local K, C, L = KkthnxUI:unpack()

local Config = KkthnxUIDataPerChar.Movers
local Data = KkthnxUIDataPerChar

C.ActionBar.EquipBorder = true
C.ActionBar.RightBarsMouseover = false
C.ActionBar.StanceBarMouseover = false
C.ActionBar.ToggleMode = false
C.Announcements.PullCountdown = false
C.Automation.AutoCollapse = false
C.Automation.AutoInvite = true
C.Automation.LoggingCombat = true
C.Automation.TabBinder = true
C.Automation.ScreenShot = true
C.Auras.CastBy = true
C.Bags.Enable = false
C.Blizzard.ColorTextures = true
C.Blizzard.ReputationGain = true
C.Chat.TabsMouseover = true
C.Chat.TabsOutline = true
C.DataText.Location = false
C.DataText.LocalTime = false
C.DataText.BottomBar = false
C.Filger.ShowTooltip = true
C.Misc.AFKCamera = true
C.Misc.AlreadyKnown = true
C.Misc.BGSpam = true
C.Misc.ColorPicker = true
C.Misc.MoveBlizzard = true
C.Misc.Combat = false
C.RaidCD.Enable = true
C.RaidCD.Height = 15
C.RaidCD.Width = 186
C.RaidCD.UpWards = false
C.RaidCD.Expiration = false
C.RaidCD.ShowSelf = true
C.RaidCD.ShowIcon = true
C.RaidCD.ShowInRaid = true
C.RaidCD.ShowInParty = true
C.RaidCD.ShowInArena = true
C.Skins.DBM = true
C.Skins.DBMMove = true
C.Skins.MinimapButtons = true
C.Skins.Skada = true
C.Skins.Recount = true
C.Skins.WeakAuras = true

Config.PlayerCastbar = {"BOTTOM", "ActionBarAnchor", "BOTTOM", 2.9, 169}
